# Generated by Django 4.1.3 on 2022-12-14 01:34

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('tfno', models.CharField(max_length=50)),
                ('apto', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TarjetaEstiba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_serie', models.CharField(max_length=255, unique=True)),
                ('precio', models.IntegerField()),
                ('cant_medi', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['no_serie', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('no_lote', models.CharField(max_length=255, unique=True)),
                ('fecha_cad', models.DateField(default=datetime.datetime(2027, 12, 13, 1, 34, 37, 462546, tzinfo=datetime.timezone.utc))),
                ('tarjeta_estiba_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.tarjetaestiba')),
                ('tipo_medicamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tipomedicamento')),
            ],
            options={
                'ordering': ['fecha_cad', 'no_lote', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_medicamento', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('medicamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.medicamento')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('tarjeta_bancaria', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('total_pagado', models.IntegerField()),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.medicamento')),
            ],
        ),
    ]
