# Generated by Django 4.1.3 on 2023-01-08 14:52

import datetime
import django.core.validators
from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_compra_options_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main_app.models.OwnUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='compra',
            name='tarjeta_bancaria',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^(9224|9225|9200|9235)(9598|1299|0699)\\d{8}$', 'Tarjeta bancaria invalida')]),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_cad',
            field=models.DateField(default=datetime.datetime(2028, 1, 7, 14, 52, 44, 623674, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellidos',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-záéíóú]{3,}(\\s[A-Za-záéíóú]{3,})?$', 'El/Los apellido(s) solo admite(n) letras')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='apto',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^([0-1][0-5]?[0-9]|\\d{2})[1-3][0-1][0-9]$', 'Apartamento UCI invalido')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])\\d{5}$', 'Carnet de identidad invalido')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-záéíóú]{3,}(\\s[A-Za-záéíóú]{3,})?$', 'El nombre solo admite letras')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='tfno',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\+53\\d{8}$', 'Telefono invalido')]),
        ),
    ]
