# Generated by Django 4.1.3 on 2023-01-11 02:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_medicamento_fecha_cad_alter_user_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3, 'La cantidad debe ser menor o igual a 3'), django.core.validators.MinValueValidator(1, 'La cantidad al menos debe ser 1')]),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_cad',
            field=models.DateField(default=datetime.datetime(2028, 1, 10, 2, 54, 41, 365099, tzinfo=datetime.timezone.utc)),
        ),
    ]
