# Generated by Django 4.1.3 on 2023-01-12 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_compra_cantidad_alter_medicamento_fecha_cad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_cad',
            field=models.DateField(default=datetime.datetime(2028, 1, 11, 3, 54, 6, 992923, tzinfo=datetime.timezone.utc)),
        ),
    ]
