# Generated by Django 4.1.3 on 2023-01-20 00:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_medicamento_fecha_cad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_cad',
            field=models.DateField(default=datetime.datetime(2028, 1, 19, 0, 34, 10, 881714, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='no_lote',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z/d]**$', 'Valores invalidos, entre letras y números solamente')]),
        ),
    ]
