# Generated by Django 4.1.3 on 2023-01-20 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_medicamento_fecha_cad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_cad',
            field=models.DateField(default=datetime.datetime(2028, 1, 19, 0, 35, 21, 730023, tzinfo=datetime.timezone.utc)),
        ),
    ]
