# Generated by Django 4.1.3 on 2023-01-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_medicamento_fecha_cad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_cad',
            field=models.DateField(),
        ),
    ]
